// Generated by CoffeeScript 1.7.1
(function() {
  var test, tests, _i, _len;

  tests = ['./views/header-view-test', './views/modal-login-page-view-test'];

  for (_i = 0, _len = tests.length; _i < _len; _i++) {
    test = tests[_i];
    require(test);
  }

}).call(this);
